# Algoritmo Simplex

## Dados Pessoais:
* **Nome**: Gabriel Castelo Branco Rocha Alencar Pinto
* **Matrícula**: 2020006523

In [1]:
import modules.linearIndependence as li
import modules.treatFunctions as tf
import modules.simplex as sp
import numpy as np

### Tratando as entradas

Para poder realizar as PL's, primeiramente é necessário realizar o processamento da entrada. Isso consiste em separar as linhas da entrada em: Matriz de Restrições, Vetor de Custos, número de restrições e Número de Variáveis.

In [2]:
m, cost, res, var = tf.input_treat(f'./test/Testes/01')


### Iniciando o SIMPLEX

Em seguida, com os dados do problema prontos, devem ser estes colocados na FPI, permitindo fazer um tableau de maneira mais eficiente.


In [3]:
s = sp.LinearProgram(var, res, cost, m)

s.makeFPI()

s.getSimplexMode()

simplexRunner = sp.Simplex(s)

simplexRunner.runSimplex()


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Testes 

In [ ]:
for i in range(1, 15):
  if i < 10:
    m, cost, res, var = tf.input_treat(f'./test/0{i}')
    lp = sp.LinearProgram(var, res, cost, m)
    lp.makeFPI()
    lp.getSimplexMode()
    print(lp)
    
  else:
    m, cost, res, var = tf.input_treat(f'./test/{i}')
    lp = sp.LinearProgram(var, res, cost, m)
    lp.makeFPI()
    lp.getSimplexMode()
    print(lp)


---------------------------------------------
| INFORMAÇÕES DA PROGRAMAÇÃO LINEAR| 

- Número de variáveis: 3;

- Número de Restrições: 3 

- Vetor de Custos: [2. 4. 8. 0. 0. 0.] 

- Vetor de Resultados: [[1. 1. 1.]]

- Usar Simplex Dual? False 

- Matriz de Restrições: 
 [[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]] 

----------------------------------------------
        

---------------------------------------------
| INFORMAÇÕES DA PROGRAMAÇÃO LINEAR| 

- Número de variáveis: 3;

- Número de Restrições: 4 

- Vetor de Custos: [1. 1. 1. 0. 0. 0. 0.] 

- Vetor de Resultados: [[-1. -1. -1. -1.]]

- Usar Simplex Dual? False 

- Matriz de Restrições: 
 [[1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 0. 0. 1.]] 

----------------------------------------------
        

---------------------------------------------
| INFORMAÇÕES DA PROGRAMAÇÃO LINEAR| 

- Número de variáveis: 3;

- Número de Restrições: 2 

- Vetor de Custos: [1. 0