# Algoritmo Simplex

## Dados Pessoais:
* **Nome**: Gabriel Castelo Branco Rocha Alencar Pinto
* **Matrícula**: 2020006523

In [1]:
import modules.linearIndependence as li
import modules.treatFunctions as tf
import modules.simplex as sp

### Tratando as entradas

Para poder realizar as PL's, primeiramente é necessário realizar o processamento da entrada. Isso consiste em separar as linhas da entrada em: Matriz de Restrições, Vetor de Custos, número de restrições e Número de Variáveis.

In [2]:
m, cost, res, var = tf.input_treat(f'./test/01')


### Iniciando o SIMPLEX

Em seguida, com os dados do problema prontos, devem ser estes colocados na FPI, permitindo fazer um tableau de maneira mais eficiente.


In [3]:
s = sp.LinearProgram(var, res, cost, m)

s.makeFPI()

print(s)

simplexRunner = sp.Simplex(s)
simplexRunner.runSimplex()

print(simplexRunner)


---------------------------------------------
| INFORMAÇÕES DA PROGRAMAÇÃO LINEAR| 

- Número de variáveis: 5;

- Número de Restrições: 5 

- Vetor de Custos: [-3.  0. -7. -5.  8.  0.  0.  0.  0.  0.] 

- Vetor de Resultados: [ 6.  6. -2. -7. -2.]

- Matriz de Restrições: 
 [[ 2. -1.  1. -1. -2.  1.  0.  0.  0.  0.]
 [-1.  2. -1.  0. -2.  0.  1.  0.  0.  0.]
 [ 2.  2.  2. -1.  0.  0.  0.  1.  0.  0.]
 [ 2. -1.  0. -2.  2.  0.  0.  0.  1.  0.]
 [-2.  2.  2. -2. -2.  0.  0.  0.  0.  1.]] 

----------------------------------------------
        

---------------------------------------------
| INFORMAÇÕES DA PROGRAMAÇÃO LINEAR| 

- Número de variáveis: 5;

- Número de Restrições: 5 

- Vetor de Custos: [-67. -64. -71. -69. -56. -64. -64. -64. -64. -64.] 

- Vetor de Resultados: [ 6.   6.  -2.  -3.5 -2. ]

- Matriz de Restrições: 
 [[-2.   1.  -1.   1.   2.  -1.   0.   0.   0.   0. ]
 [ 1.  -2.   1.   0.   2.   0.  -1.   0.   0.   0. ]
 [ 2.   2.   2.  -1.   0.   0.   0.   1.   0.   0. ]
